routes:
  /sitemap/:
    template: sitemap
    content_type: text/xml

collections:
  /:
    permalink: '/{year}/{month}/{day}/{slug}/'
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
